Exclude Ruby 3.4 on windows-2022 due to unsupported version
It seems that Ruby 3.4 is not yet supported by ruby/setup-ruby.

## GitHub Actions Error message

```
Error: Error: Unknown version 3.4 for ruby on windows-2022
        Available versions for ruby on windows-2022: 2.0.0, 2.1.9, 2.2.6, 2.3.0, 2.3.1, 2.3.3, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.9, 2.4.10, 2.5.0, 2.5.1, 2.5.3, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.6.9, 2.6.10, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, head, mingw, mswin, ucrt
        Make sure you use the latest version of the action with - uses: ruby/setup-ruby@v1
    at validateRubyEngineAndVersion (D:\a_actions\ruby\setup-ruby\v1\dist\index.js:65886:13)
    at setupRuby (D:\a_actions\ruby\setup-ruby\v1\dist\index.js:65786:15)
    at run (D:\a_actions\ruby\setup-ruby\v1\dist\index.js:65745:11)
    at D:\a_actions\ruby\setup-ruby\v1\dist\index.js:65944:40
    at D:\a_actions\ruby\setup-ruby\v1\dist\index.js:65946:3
    at Object.<anonymous> (D:\a_actions\ruby\setup-ruby\v1\dist\index.js:65949:12)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
```